<template>
    <div>
        <div>
            合同详情
        </div>
    </div>
</template>
<script>
    export default {
        data(){
            return{
                formItem:{
                    name:'',
                    start:0,
                    length:10,
                },
            }
        },
        methods:{
        },
    }
</script>